name: CI/CD for Docker Image Deployment
on:
push:
branches:
- main
jobs:
update_docker_image:
name: Build and Push Docker Image
runs-on: ubuntu-latest
steps:
- name: Check out repository
uses: actions/checkout@v4
- name: Log in to Docker Hub
uses: docker/login-action@v2
with:
username: ${{ secrets.DOCKER_USERNAME }}
password: ${{ secrets.DOCKER_PASSWORD }}
- name: Build and push Docker image
uses: docker/build-push-action@v5
with:
context: .
push: true
tags: daniela0919/hello-world-html:latest
deploy_to_ec2:
name: Deploy Docker Container to EC2
runs-on: ubuntu-latest
needs: update_docker_image
steps:
- name: Set up SSH key
run: |
mkdir -p ~/.ssh
echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa
- name: Deploy to EC2 Instance 1
uses: appleboy/ssh-action@v0.1.6
with:
host: ${{ secrets.EC2_INSTANCE_1 }}
username: ec2-user
key: ${{ secrets.EC2_SSH_KEY }}
port: 22
script: |
docker stop html-container || true
docker rm html-container || true
docker pull daniela0919/hello-world-html:latest
docker run -d --name html-container -p 80:80 daniela0919/hello-world-html:latest
- name: Deploy to EC2 Instance 2
uses: appleboy/ssh-action@v0.1.6
with:
host: ${{ secrets.EC2_INSTANCE_2 }}
username: ec2-user
key: ${{ secrets.EC2_SSH_KEY }}
port: 22
script: |
docker stop html-container || true
docker rm html-container || true
docker pull daniela0919/hello-world-html:latest
docker run -d --name html-container -p 80:80 daniela0919/hello-world-html:latest
